# Generated by Django 4.1.7 on 2023-03-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('thumbnail_url', models.URLField(max_length=1000)),
                ('publish_datetime', models.DateTimeField()),
                ('url', models.URLField(max_length=1000)),
            ],
        ),
    ]
